Models/Carrito.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SuperMerk2.Models
{
    public class Carrito
    {
        [Key]
        public int carritoId { get; set; }
        [ForeignKey("clienteDatos")]
        public int clienteId { get; set; }
        public ClienteDatos clienteDatos { get; set; }
        public List<ProductoDeCarrito> listaProductosCarrito { get; set; }

        [Required]
        public bool finalizado { get; set; }
    }
}

Controllers/AdminController.cs
using SuperMerk2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperMerk2.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Admin()
        {
            Usuario usuario = Session["UserSession"] as Usuario;
            if (usuario != null)
            {
                if (usuario.esAdmin)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("LogIn", "Login");
            }
            
        }
    }
}

Controllers/ArchivoController.cs
using SuperMerk2.Business;
using SuperMerk2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperMerk2.Controllers
{
    public class ArchivoController : Controller
    {
        [HttpGet]
        public void DescargarXMLCarrito(int idCarrito)
        {
            ArchivosBL archivo = new ArchivosBL();
            Carrito carrito = new CarritoBL().getDataCarritoFull(idCarrito);

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename = carrito.xml");

            Response.ContentType = "text/xml";

            archivo.serializarAXML(carrito, Response.OutputStream);
            Response.End();
        }

        [HttpGet]
        public void DescargarXMLBitacora(string username)
        {
            if(username != null)
            {
                ArchivosBL archivo = new ArchivosBL();
                List<Bitacora> bitacora = new BitacoraBL().traerBitacoraUsuario(username);

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename = bitacora.xml");

                Response.ContentType = "text/xml";

                archivo.serializarAXML(bitacora, Response.OutputStream);
                Response.End();
            }
            else
            {
                ArchivosBL archivo = new ArchivosBL();
                List<Bitacora> bitacora = new BitacoraBL().traerBitacoraCompleta();

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename = bitacora.xml");

                Response.ContentType = "text/xml";

                archivo.serializarAXML(bitacora, Response.OutputStream);
                Response.End();
            }

        }
    }
}

Controllers/CarritoController.cs
using SuperMerk2.Business;
using SuperMerk2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperMerk2.Controllers
{
    public class CarritoController : Controller
    {
        public ActionResult MostrarCarrito()
        {
            var carrito = Session["Carrito"] as Carrito;
            return View(carrito);
        }

        public ActionResult ListaCarrito()
        {
            Usuario usuario = Session["UserSession"] as Usuario;
            if (usuario != null)
            {
                if (usuario.esAdmin)
                {
                    CarritoBL biz = new CarritoBL();                    
                    var carrito = biz.GetAll();
                    return View(carrito);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("LogIn", "Login");
            }

        }

        public ActionResult ListaCarritoxCliente(string user)
        {
            Usuario usuario = Session["UserSession"] as Usuario;
            if (usuario != null)
            {
                if (usuario.esAdmin)
                {
                    DatosClienteBL bizcl = new DatosClienteBL();
                    CarritoBL biz = new CarritoBL();
                    var cliente = bizcl.getDataCliente(user);
                    var carrito = biz.TraerCarritoCliente(cliente);
                    return View(carrito);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("LogIn", "Login");
            }

        }

        public ActionResult ListarDetalleCarrito(int id)
        {
            Usuario usuario = Session["UserSession"] as Usuario;
            if (usuario != null)
            {
                if (usuario.esAdmin)
                {
                    ProductoCarritoBL biz = new ProductoCarritoBL();
                    var carrito = biz.getProductosCarritoFull(id);
                    return View(carrito);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("LogIn", "Login");
            }

        }
        // POST: Carrito/Delete/5
        [HttpGet]
        public ActionResult EliminarProducto(int carrito, int productoEliminar)
        {
            Business.CarritoBL c = new Business.CarritoBL();
            var carritoActualziado = c.borrarItemCarrito(carrito, productoEliminar);
            Session["Carrito"] = carritoActualziado;
            //Log Evento
            new BitacoraController().RegistrarEvento(Session["UserSession"] as Usuario, "Elimino un producto de su carrito");
            return View("MostrarCarrito", carritoActualziado);
        }


    }
}

Controllers/VentasController.cs
using SuperMerk2.Business;
using SuperMerk2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperMerk2.Controllers
{
    public class VentasController : Controller
    {
        // GET: Ventas/Create
        [HttpPost]
        public ActionResult Checkout(int idCarrito)
        {
            VentasBL bl = new VentasBL();
            //Verifico que nada exceda stock por las dudas
            Carrito carr = new CarritoBL().getDataCarritoFull(idCarrito);
            carr.clienteDatos = new ClienteDatos();
            var usuario = Session["UserSession"] as Usuario;
            carr.clienteDatos.username = usuario.username;
            if (bl.SuficienteStock(carr))
            {
                //Si hay suficiente stock, hago checkout
                bl.Checkout(carr);
                Session["Carrito"] = null;
            }
            return RedirectToAction("Index","Home");
        }

        
    }
}

Views/Carrito/ListaCarrito.cshtml
@model IEnumerable<SuperMerk2.Models.Carrito>
@using SuperMerk2.Models;
@using SuperMerk2.Business;

@{
    ViewBag.Title = "ListarBitacora";
    Layout = "~/Views/Shared/_Layout.cshtml";
    UsuarioBL biz = new UsuarioBL();
    var usuarios = biz.Listar();
    string usuario = "";
}
@{
    ViewBag.Title = "ListaCarrito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/Bitacora/Bitacora.css" rel="stylesheet" />
    <link href="~/Content/Bitacora/Bitacora.css" rel="stylesheet" />

    <title> Lista Carrito</title>
</head>
<body>

    <div class="dataTable-Container">
        <table class="datatable">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.clienteDatos.username)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.finalizado)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                if (usuario != "")
                {
                    if (item.clienteDatos.username == usuario)
                    {
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.clienteDatos.username)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.finalizado)
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", new { id = item.carritoId })
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.clienteDatos.username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.finalizado)
                        </td>
                        <td>
                            @Html.ActionLink("Detalle", "ListarDetalleCarrito", "Carrito", new { id = item.carritoId }, new { }) |
                            @Html.ActionLink("Descargar","DescargarXMLCarrito", "Archivo", new { idCarrito = item.carritoId }, new { })

                        </td>
                    </tr>
                }

            }
        </table>


    </div>
    <div>
        <p>
            <a><i class='bx bx-arrow-back'></i> </i>@Html.ActionLink("Volver", "Admin", "Admin")</a>
        </p>
    </div>
</body>
</html>

Views/Carrito/ListarDetalleCarrito.cshtml
@model IEnumerable<SuperMerk2.Models.ProductoDeCarrito>

@{
    ViewBag.Title = "ListarDetalleCarrito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/Bitacora/Bitacora.css" rel="stylesheet" />
    <title> Lista Bitacora</title>
</head>
<body>
    <div class="dataTable-Container">
        <table class="datatable">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.producto.nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.cantidadItems)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.producto.nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cantidadItems)
                    </td>
                </tr>
            }
        </table>
    </div>
    <div>
        <p>
            <a><i class='bx bx-arrow-back'></i> </i>@Html.ActionLink("Volver", "ListaCarrito", "Carrito")</a>
        </p>
    </div>
</body>
</html>

Views/Carrito/MostrarCarrito.cshtml
@model SuperMerk2.Models.Carrito

@{
    ViewBag.Title = "MostrarCarrito";
    Layout = "~/Views/Shared/_Layout.cshtml";
    double total = 0;
}

<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/Bitacora/Bitacora.css" rel="stylesheet" />
    <script src="~/Scripts/TS/app.js"></script>
    <title> Lista Bitacora</title>
    <style>
        .button {
            top: 50%;
            left: 50%;
            transform: translate(-50, -50);
        }

        .button {
            background: none;
            color: #000;
            width: 176px;
            height: 45px;
            border: 1px solid #338033;
            font-size: 18px;
            border-radius: 4px;
            transition: .6s;
            overflow: hidden;
            margin-top: 21px;
        }

        a {
            text-decoration: none;
            color: #000;
            font-size: 20px;
        }

        .button:focus {
            outline: none;
        }

        .button:before {
            content: '';
            display: block;
            background: rgb(140,198,63);
            width: 60px;
            height: 100%;
            left: 0;
            top: 0;
            opacity: .5;
            filter: blur(30px);
            transform: translateX(-130px) skewX(-15deg);
        }

        .button:after {
            content: '';
            display: block;
            position: absolute;
            background: rgba(255,255,255,.2);
            width: 30px;
            height: 100%;
            left: 30px;
            top: 0;
            opacity: 0;
            filter: blur(30px);
            transform: translateX(-100px) scaleX(-15deg);
        }

        .button:hover {
            background: rgb(140,198,63);
            cursor: pointer;
        }

            .button:hover:before {
                transform: translateX(300px) skewX(-15deg);
                opacity: .6;
                transition: .7s;
            }

            .button:hover:after {
                transform: translateX(300px) skewX(-15deg);
                opacity: 1;
                transition: .7s;
            }

    </style>
</head>
<body>
    <div class="dataTable-Container">
        @if (Model == null)
        {
            <h3>No hay items en el carrito</h3>
            <img height="250" width="250" src="~/Content/Imagenes/Tomate_Triste.png" />
        }
        else
        {
            @Html.BeginForm("Checkout","Ventas",new { idCarrito = Model.carritoId })
            {
                <table class="datatable">
                    <tr>
                        <th>
                            <label>Categoria</label>
                        </th>
                        <th>
                            <label>Producto</label>
                        </th>
                        <th>
                            <label>Precio Unitario</label>
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.listaProductosCarrito)
                    {
                        total += item.producto.precio;
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.producto.categoria.nombreCategoria)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.producto.nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.producto.precio)
                            </td>
                            <th>@Html.ActionLink("Eliminar", "EliminarProducto", "Carrito", new { carrito = item.carritoId, productoEliminar = item.itemCarritoId }, new { })</th>
                        </tr>
                    }


                </table>
            }
            <input type="submit" value="CheckOut" class="button" />
        }
        <br/>
        <input class="button" type="button" value="Mostrar total" onclick="mostrarComprar()" />
        <p id="Precio" style="display:none">Total: $@total</p>
    </div>
</body>
</html>