Models/Bitacora.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SuperMerk2.Models
{
    public class Bitacora
    {
        [Key]
        public int idBitacora { get; set; }
        [ForeignKey("usuario")]
        [StringLength(100, MinimumLength = 1)]
        public string username { get; set; }
        public Usuario usuario { get; set; }

        [Required]
        public string descripcion { get; set; }
        [Required]
        public DateTime fechaHora { get; set; }
        public Bitacora()
        {

        }
        public Bitacora(Usuario user, string evento)
        {
            username = user.username;
            descripcion = evento;
            fechaHora = DateTime.Now;
        }
    }
}

Controllers/ArchivoController.cs
using SuperMerk2.Business;
using SuperMerk2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperMerk2.Controllers
{
    public class ArchivoController : Controller
    {
        [HttpGet]
        public void DescargarXMLCarrito(int idCarrito)
        {
            ArchivosBL archivo = new ArchivosBL();
            Carrito carrito = new CarritoBL().getDataCarritoFull(idCarrito);

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename = carrito.xml");

            Response.ContentType = "text/xml";

            archivo.serializarAXML(carrito, Response.OutputStream);
            Response.End();
        }

        [HttpGet]
        public void DescargarXMLBitacora(string username)
        {
            if(username != null)
            {
                ArchivosBL archivo = new ArchivosBL();
                List<Bitacora> bitacora = new BitacoraBL().traerBitacoraUsuario(username);

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename = bitacora.xml");

                Response.ContentType = "text/xml";

                archivo.serializarAXML(bitacora, Response.OutputStream);
                Response.End();
            }
            else
            {
                ArchivosBL archivo = new ArchivosBL();
                List<Bitacora> bitacora = new BitacoraBL().traerBitacoraCompleta();

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename = bitacora.xml");

                Response.ContentType = "text/xml";

                archivo.serializarAXML(bitacora, Response.OutputStream);
                Response.End();
            }

        }
    }
}

Controllers/BitacoraController.cs
using SuperMerk2.Business;
using SuperMerk2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperMerk2.Controllers
{
    public class BitacoraController : Controller
    {
        // GET: Bitacora
        public ActionResult ListarBitacora()
        {
            Usuario usuario = Session["UserSession"] as Usuario;
            if (usuario != null)
            {
                if (usuario.esAdmin)
                {           
                    RedirectLogin();
                    BitacoraBL biz = new BitacoraBL();
                    var bitacora = biz.traerBitacoraCompleta();
                   return View(bitacora);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("LogIn", "Login");
            }

        }
        [HttpPost]
        public ActionResult ListarBitacoraPorUsuario(string filtro)
        {
            Usuario usuario = Session["UserSession"] as Usuario;
            if (usuario != null)
            {
                if (usuario.esAdmin)
                {            
                    BitacoraBL biz = new BitacoraBL();
                    var bitacora = biz.traerBitacoraUsuario(filtro);
                    TempData["UsuarioElegido"] = filtro;
                    TempData.Keep();
                    return PartialView("ListarBitacora", bitacora);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("LogIn", "Login");
            }

        }


        public void RegistrarEvento(Usuario user, string descripcion)
        {
            BitacoraBL biz = new BitacoraBL();
            biz.registrarEvento(user, descripcion);
        }

        private void RedirectLogin()
        {
            if (Session["UserSession"] == null)
            {
                RedirectToAction("LogIn", "Login");
            }
        }
    }
}

Views/Bitacora/ListarBitacora.cshtml
@model IEnumerable<SuperMerk2.Models.Bitacora>
@using SuperMerk2.Models;
@using SuperMerk2.Business;

@{
    ViewBag.Title = "ListarBitacora";
    Layout = "~/Views/Shared/_Layout.cshtml";
    UsuarioBL biz = new UsuarioBL();
    var usuarios = biz.Listar();
    var lstBitacora = Model.ToList();
    string usuario = "";
}

<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/Bitacora/Bitacora.css" rel="stylesheet" />
    <title> Lista Bitacora</title>
</head>
<body>
    @using (Html.BeginForm("ListarBitacoraPorUsuario", "Bitacora"))
    {
        <div class="select-username">
            <select id="filtro" name="filtro">
                @foreach (var user in usuarios)
                {
                    <option>@user.username</option>
                }
            </select>
            <input type="submit" value="search" class="button" />
        </div>

    }



<div class="dataTable-Container">
    <table class="datatable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaHora)

            </th>
        </tr>

        @foreach (var item in Model)
        {
            if (usuario != "")
            {
                if (item.username == usuario)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.descripcion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.fechaHora)
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fechaHora)
                    </td>
                </tr>
            }

        }
    </table>
    <form>
        <input type="button" class="button" value="Create" onclick="location.href=' @Url.Action("DescargarXMLBitacora", "Archivo", new { username = TempData["UsuarioElegido"] })'" />
    </form>

</div>
</body>
</html>